"""
Run the whole pipeline with one command:

    python3 src/run_all.py

    1. regenerate the synthetic survey        -> data/*.csv
    2. run the three analyses                 -> reports/figures/*.svg
    3. assemble the read-out                  -> reports/survey_report.md
    4. build the interactive dashboard        -> dashboard.html

Deterministic: same seed, same numbers, same charts, every time.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import analysis_drivers
import analysis_scores
import analysis_text
import build_dashboard
import generate_survey
from surveylib import FIELD_WINDOW, MIN_GROUP, ROOT, SURVEY_NAME

REPORT = ROOT / "reports" / "survey_report.md"

HEADER = f"""# {SURVEY_NAME} - survey read-out

**Fieldwork:** {FIELD_WINDOW}
**Population:** a synthetic European services group - 3,800 employees, 149 teams,
four countries
**Generated by:** `python3 src/run_all.py` - every number, chart and quotation below is
reproduced from the code in this repository

> The survey, the answers and the comments are synthetic, generated with a fixed seed by
> `src/generate_survey.py`. No real employee ever wrote any of this. What is meant to be
> judged is the method: how participation is checked before results are quoted, how drivers
> are separated from noise, and how free text is scored before it is believed.

---

"""

FOOTER = f"""
---

## Method, assumptions and limits

**Favourable scoring.** A dimension's score is the share of answers in the top two points
of the five-point scale, pooled across the items in that dimension. Every rate is reported
with a **Wilson confidence interval**, which behaves properly near 0% and 100% where the
textbook interval produces impossible bounds. Group comparisons use a two-proportion
z-test rather than an eyeballed gap.

**Confidentiality.** No score is published for any group below **{MIN_GROUP} respondents** -
in the report, in the team lists, and in the dashboard, where filtering below the threshold
masks the tiles as well as the charts. This is the promise that makes people answer
honestly; it is worth more than any single cut of the data.

**Key driver analysis.** Engagement is modelled from the eight dimension scores using
Johnson's relative weight analysis. Ordinary regression coefficients are unstable when
predictors are as correlated as survey dimensions are: they hand shared variance to
whichever driver wins a near-tie. Relative weights split the explained variance sensibly,
and a **bootstrap over resampled respondents** shows which parts of the resulting ranking
survive resampling and which do not. Standardised betas and simple correlations are
reported alongside, so the reader can see all three agree on the top of the list.

**Free text.** Themes are assigned by a keyword lexicon and sentiment by a word list with
negation handling - both in `src/textlib.py`, both readable and arguable. Neither is a
language model, and the report states the measured precision, recall and error rates
before drawing on the results. Comments are analysed only in aggregate; nothing is ever
inferred about an individual, and verbatims are published only from groups above the
threshold, after an automated pass that strips names, emails and phone numbers.

**Limits.** One survey, one moment, one organisation. Cross-sectional data cannot establish
that improving a driver *causes* engagement to rise - the driver analysis ranks
associations, and the report says so wherever a number could be read as a promise.
Non-response is not random: the groups least likely to answer are the ones under most
pressure, so company-level scores are more likely to be flattering than harsh.
"""


def main() -> None:
    print("1/4  generating the synthetic survey")
    generate_survey.main()

    print("\n2/4  running analyses")
    sections = []
    for name, module in (("participation & scores", analysis_scores),
                         ("key drivers", analysis_drivers),
                         ("free text", analysis_text)):
        sections.append(module.run())
        print(f"     - {name}")

    print("\n3/4  writing the read-out")
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    body = "\n\n".join(section.rstrip() + "\n" for section in sections)
    REPORT.write_text(HEADER + body + FOOTER, encoding="utf-8")
    figures = sorted((ROOT / "reports" / "figures").glob("*.svg"))
    print(f"     reports/survey_report.md  ({REPORT.stat().st_size / 1024:.0f} KB)")
    print(f"     reports/figures/          ({len(figures)} charts)")

    print("\n4/4  building the dashboard")
    build_dashboard.main()

    print("\nDone. Open dashboard.html in a browser, or read reports/survey_report.md.")


if __name__ == "__main__":
    main()
